getgauge/gauge-repository

java-install.json

adding gauge-java 0.3.4

---

js-install.json

Please review and see if this is alright, and if this is the right place to put this.

Add gauge-js v0.1.1

---

templates/ruby_selenium/Gemfile
templates/ruby_selenium/metadata.json
templates/ruby_selenium/step_implementations/driver.rb

Install dependencies locally in the vendor/bundle folder
Default to chrome if the 'browser' environment variable is not set.

Add chromedriver to the bundle install

---

templates/js_puppeteer/env/default/default.properties
templates/js_puppeteer/env/default/js.properties
templates/js_puppeteer/manifest.json
templates/js_puppeteer/metadata.json
templates/js_puppeteer/package.json
templates/js_puppeteer/specs/example.spec
templates/js_puppeteer/tests/step_implementation.js

Add sample specification and implementations for headless browser testing

Adding js puppeteer template for headless chrome testing

---

templates/js/tests/step_implementation.js

Moving implementation to the new format.

Removed deprecated definition of steps and hooks.

---

templates/js_webdriver/.gitignore
templates/js_webdriver/env/default/default.properties
templates/js_webdriver/env/default/js.properties
templates/js_webdriver/manifest.json
templates/js_webdriver/metadata.json
templates/js_webdriver/package.json
templates/js_webdriver/specs/example.spec
templates/js_webdriver/tests/step_implementation.js

Sample for running tests using http://webdriver.io/

Add Javascript WebDriver template

---

testrail-install.json

added `testrail.json` for the TestRail plugin

install file for testrail plugin

---

json-report-install.json

Release: https://github.com/apoorvam/json-report/releases/tag/0.3.0

Update json-report-install to include v0.3.0

---

templates/js_webdriver/package.json

Solving issue #37 - Update webdriveio on js_webdriver to version 5.14.4

Update webdriveio on js_webdriver

---

reportportal-install.json

Just new version is available.

New version for reportportal

---

reportportal-install.json

Just up version of reportportal pluign

New ReportPortal plugin v1.4.0

---

reportportal-install.json

ReportPortal plugin v1.4.1

---

reportportal-install.json

Bump new ReportPortal plugin 1.5.0

---

reportportal-install.json

New version of ReportPortal plugin

---

java-install.json

Corrects the download urls for gauge-java 0.7.9

---

reportportal-install.json

Just new version of ReportPortal plugin is available

New ReportPortal plugin version 1.8.0

---

reportportal-install.json

New version 1.9.0 of reportportal plugin

---

reportportal-install.json

Just new version of ReportPortal plugin v1.11 released.

ReportPortal plugin update

---

reportportal-install.json

Just new v1.11.1 of ReportPortal plugin.

New ReportPortal version

---

dotnet-install.json

Signed-off-by: sriv <srikanth.ddit@gmail.com>

update dotnet -> 0.3.1

---

jira-install.json

Bump Jira plugin to version 0.1.1

---

jira-install.json

Bump jira plugin to 0.1.2

---

jira-install.json

Bump Jira plugin to 0.1.3

---

jira-install.json

Bump jira plugin to 0.1.4

---

jira-install.json

Bump Jira plugin to 0.1.7

---

jira-install.json

Bump Jira plugin to 0.1.8

---

jira-install.json

Signed-off-by: John Boyes 154404+johnboyes@users.noreply.github.com

Bump jira plugin to 0.2.0

---

jira-install.json

Bump jira plugin to 0.2.1

---

jira-install.json

Bump Jira plugin to 0.3.0

---

jira-install.json

Bump Jira plugin to 0.4.2

---

confluence-install.json

Bump Confluence plugin to 0.16.1

---

confluence-install.json

Bump Confluence plugin to 0.17.0

---

confluence-install.json

Bump Confluence plugin to 0.18.0

---

confluence-install.json

Bump Confluence plugin to 0.18.1

---

reportportal-install.json

Added new version of Report Portal plugin v1.13.1

---

reportportal-install.json

Added new version of Report Portal plugin

Added new version of Report Portal plugin

---

reportportal-install.json

- Just new version of Report Portal plugin
- Added support of linux arm64

New Report Portal version 1.16

---

ts-install.json

Refer to the latest version of typescript plugin.

Update typescript version to 0.1.1
